# Generated by Django 5.1.3 on 2024-11-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_content', models.TextField()),
                ('email_list', models.TextField()),
                ('schedule_time', models.IntegerField()),
                ('status', models.CharField(default='Pending', max_length=20)),
            ],
        ),
    ]
